# Generated by Django 4.2.28 on 2026-02-18 10:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('ppt', 'Presentation'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to='notes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg'])])),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PastYearPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document'), ('ppt', 'Presentation'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=10)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField(help_text='Year the exam was held (e.g. 2022)')),
                ('has_solution', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, help_text='Single file upload (use PastYearPaperFile for multiple pages)', null=True, upload_to='past_year_papers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg'])])),
            ],
            options={
                'verbose_name': 'Past Year Paper',
                'verbose_name_plural': 'Past Year Papers',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PastYearPaperFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='past_year_papers/pages/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg'])])),
                ('page_number', models.PositiveIntegerField(help_text='Order/page number of this file')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Past Year Paper File',
                'verbose_name_plural': 'Past Year Paper Files',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='PastYearPaperSolutionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='past_year_papers/solutions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg'])])),
                ('page_number', models.PositiveIntegerField(help_text='Order/page number of this solution file')),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Past Year Paper Solution File',
                'verbose_name_plural': 'Past Year Paper Solution Files',
                'ordering': ['page_number'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='notes.program')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='notes.semester')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['code'], name='notes_progr_code_baecde_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['is_active'], name='notes_progr_is_acti_f5a0cd_idx'),
        ),
        migrations.AddField(
            model_name='pastyearpapersolutionfile',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_files', to='notes.pastyearpaper'),
        ),
        migrations.AddField(
            model_name='pastyearpaperfile',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_files', to='notes.pastyearpaper'),
        ),
        migrations.AddField(
            model_name='pastyearpaper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_year_papers', to='notes.subject'),
        ),
        migrations.AddField(
            model_name='pastyearpaper',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_past_year_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.subject'),
        ),
        migrations.AddField(
            model_name='note',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['semester', 'is_active'], name='notes_subje_semeste_27e46b_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='notes_subje_code_67332b_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['program', 'number'], name='notes_semes_program_3a878e_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_active'], name='notes_semes_is_acti_efdcce_idx'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('program', 'number'), name='unique_semester_per_program'),
        ),
        migrations.AddConstraint(
            model_name='pastyearpapersolutionfile',
            constraint=models.UniqueConstraint(fields=('paper', 'page_number'), name='unique_solution_page_number_per_paper'),
        ),
        migrations.AddConstraint(
            model_name='pastyearpaperfile',
            constraint=models.UniqueConstraint(fields=('paper', 'page_number'), name='unique_page_number_per_paper'),
        ),
        migrations.AddIndex(
            model_name='pastyearpaper',
            index=models.Index(fields=['subject', '-year'], name='notes_pasty_subject_1e4c79_idx'),
        ),
        migrations.AddIndex(
            model_name='pastyearpaper',
            index=models.Index(fields=['year'], name='notes_pasty_year_a51a18_idx'),
        ),
        migrations.AddIndex(
            model_name='pastyearpaper',
            index=models.Index(fields=['is_active'], name='notes_pasty_is_acti_3c4669_idx'),
        ),
        migrations.AddConstraint(
            model_name='pastyearpaper',
            constraint=models.UniqueConstraint(fields=('subject', 'year'), name='unique_paper_per_subject_per_year'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='notes_note_created_cf5022_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['subject', '-created_at'], name='notes_note_subject_ef21d5_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_active'], name='notes_note_is_acti_0342fa_idx'),
        ),
    ]
