# Generated by Django 4.2.28 on 2026-03-11 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='notes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='pastyearpaper',
            name='file',
            field=models.FileField(blank=True, help_text='Single file upload (use PastYearPaperFile for multiple pages)', null=True, upload_to='past_year_papers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='pastyearpaperfile',
            name='file',
            field=models.FileField(upload_to='past_year_papers/pages/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='pastyearpapersolutionfile',
            name='file',
            field=models.FileField(upload_to='past_year_papers/solutions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
