# Generated by Django 4.2.28 on 2026-03-30 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_file_alter_pastyearpaper_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastyearpaper',
            options={'ordering': ['-created_at'], 'verbose_name': 'Past Year Paper', 'verbose_name_plural': 'Past Year Papers'},
        ),
        migrations.RemoveConstraint(
            model_name='pastyearpaper',
            name='unique_paper_per_subject_per_year',
        ),
        migrations.RemoveIndex(
            model_name='pastyearpaper',
            name='notes_pasty_subject_1e4c79_idx',
        ),
        migrations.AlterField(
            model_name='pastyearpaper',
            name='file',
            field=models.FileField(blank=True, help_text='Single file upload (use Page Files section for multiple pages)', null=True, upload_to='past_year_papers/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'zip', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='pastyearpaper',
            name='year',
            field=models.CharField(help_text='Year the exam was held (e.g. 2080, Back 2079, Chance 2078/79)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='pastyearpaper',
            index=models.Index(fields=['subject', 'year'], name='notes_pasty_subject_f121a1_idx'),
        ),
    ]
